#ifndef MUSIC_H
#define MUSIC_H

#define MUSIC_DURATION 10
#define MUSIC_SAMPLERATE 44100
#define MUSIC_CHANNELS 2

#define MUSIC_NUMSAMPLES (MUSIC_DURATION * MUSIC_SAMPLERATE)
#define MUSIC_BUFFERSIZE (MUSIC_NUMSAMPLES * MUSIC_CHANNELS)


#endif//MUSIC_H

